packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vite-plus: 0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24

minimumReleaseAgeExclude:
  - '@base-ui/react@1.5.0'
  - '@base-ui/utils@0.2.9'
  - '@cloudflare/vite-plugin@1.37.2'
  - '@shikijs/core@4.1.0'
  - '@shikijs/engine-javascript@4.1.0'
  - '@shikijs/engine-oniguruma@4.1.0'
  - '@shikijs/langs@4.1.0'
  - '@shikijs/primitive@4.1.0'
  - '@shikijs/rehype@4.1.0'
  - '@shikijs/themes@4.1.0'
  - '@shikijs/types@4.1.0'
  - '@types/node@25.9.1'
  - '@types/react@19.2.15'
  - '@typescript/native-preview-darwin-arm64@7.0.0-dev.20260519.1'
  - '@typescript/native-preview-darwin-x64@7.0.0-dev.20260519.1'
  - '@typescript/native-preview-linux-arm64@7.0.0-dev.20260519.1'
  - '@typescript/native-preview-linux-arm@7.0.0-dev.20260519.1'
  - '@typescript/native-preview-linux-x64@7.0.0-dev.20260519.1'
  - '@typescript/native-preview-win32-arm64@7.0.0-dev.20260519.1'
  - '@typescript/native-preview-win32-x64@7.0.0-dev.20260519.1'
  - '@typescript/native-preview@7.0.0-dev.20260519.1'
  - '@voidzero-dev/vite-plus-core@0.1.22'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.1.22'
  - '@voidzero-dev/vite-plus-darwin-x64@0.1.22'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.1.22'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.1.22'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.1.22'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.1.22'
  - '@voidzero-dev/vite-plus-test@0.1.22'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.1.22'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.1.22'
  - miniflare@4.20260518.0
  - shiki@4.1.0
  - vite-plus@0.1.22
  - wrangler@4.93.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - sharp
  - workerd
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
