packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - sharp
  - workerd
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
