name: CI (Main)

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true
          run-install: |
            - args: ['--frozen-lockfile']

      - name: Build
        run: vp run -r build

  check:
    name: Check
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true
          run-install: |
            - args: ['--frozen-lockfile']

      - name: Generate types
        run: vp run -r types:gen

      - name: Check
        run: vp check
